//internal package
import "./globals.css";
import { MainNav } from "@/components/main-nav";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
//internal service
import dbConnect from "@/service/dbConnect";

import { Inter } from "next/font/google";
// Load Inter font with specific options
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Customize weights
  variable: "--font-inter", // Define a CSS variable for easy use
  display: "swap", // Ensures a smooth loading experience
});

//main nav item
const navLink = [
  {
    title: "IBA",
    href: "/iba",
  },
  {
    title: "SICIP",
    href: "/sicip",
  },
  {
    title: "About",
    href: "/about",
  },
  {
    title: "Notice",
    href: "/notice",
  },
];

//meta
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//main
export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en">
      <body
        className={`${inter.variable} flex w-full min-h-screen flex-col antialiased`}
      >
        <header className=" w-full flex flex-col justify-center items-center z-40 backdrop-blur-md fixed top-0 left-0 right-0 border-b">
          <div className="container flex h-20 items-center justify-between p-6 ">
            <SessionProvider>
              <MainNav items={navLink} />
            </SessionProvider>
          </div>
        </header>
        <main className="flex-1 pt-20 flex flex-col"> {children}</main>
        <Toaster />
      </body>
    </html>
  );
}
