//internal package
import localFont from "next/font/local";
import "./globals.css";
import { MainNav } from "@/components/main-nav";
import { SessionProvider } from "next-auth/react";
import { Roboto_Slab } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner";
//internal service
import dbConnect from "@/service/dbConnect";


//font
export const roboto_slab = Roboto_Slab({
  subsets: ['latin'],
  display: 'swap',
  style: ['normal'],
  weight: ['400']
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


//main nav item
const navLink = [
  {
    title: "IBA",
    href: "/iba"
  },
  {
    title: "SICIP",
    href: "/sicip"
  },
  {
    title: "About",
    href: "/about"
  },
  {
    title: "Notice",
    href: "/notice"
  }
]

//meta data 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//main
export default async function RootLayout({ children }) {
  await dbConnect()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto_slab.className} flex w-full min-h-screen flex-col antialiased`}>
        <header className=" w-full flex flex-col justify-center items-center z-40 backdrop-blur-md fixed top-0 left-0 right-0 border-b">
          <div className="container flex h-20 items-center justify-between p-6 ">
            <SessionProvider>
              <MainNav items={navLink} />
            </SessionProvider>
          </div>
        </header>
        <main className="flex-1 pt-20 flex flex-col"> {children}</main>
        <Toaster />
      </body>
    </html>
  );
}
